### ISSUE TITLE
[2pt] CRUD for Food List

### ISSUE THREAD

**Issue by sagieramos** [sagieramos/recipe_app#5]
Implement Create, Read, and Delete operations for the Food List.

**Comment by sagieramos** [comment]
- Create Food model.
- Implement food creation form.
- Display list of user's foods.
- Implement delete functionality.

**Comment by mohamedSabry0** [comment]
- Food list should be for a given inventory (with all CRUD implementation, except for ‘update’).
- Should display the inventory details as in the wireframe.
- Should lead to a form that allows users to add new food.
